#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
if [ -e "school" ] ; then
   echo "school file exists"
   if [ ! -s "school"] ; then
      echo "school file is empty"
     elif [ -s "school" ] ; then
     	  echo "school file is not empty"
	  else
		echo "school is a regular file"
   fi
   else
	echo "school file does not exist"
fi